name: Python application test with Github Actions

on: 
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test with pytest
      run: |
        make test
